### ISSUE TITLE
Error as Codeship Service

### ISSUE THREAD

**Issue by johnallen3d** [codeship-library/aws-ecr-dockercfg-generator#2]
I'm not sure if this is the right place for this but I'm having some difficulty using this container as a service on the Codeship Docker Platform.

Here is my configuration:

```
# codeship-services.yml
bot:
  build:
    image: 8888888888888.dkr.ecr.us-east-1.amazonaws.com/bot
    dockerfile_path: Dockerfile
  cached: true
  dockercfg_service: aws_dockercfg

aws_dockercfg:
  image: codeship/aws-ecr-dockercfg-generator
  add_docker: true
  encrypted_env: aws-ecr.env.encrypted
```

```
# codeship-steps.yml
- name: test_bot
  service: bot
  command: ./script/ci
  registry: https://8888888888888.dkr.ecr.us-east-1.amazonaws.com
  dockercfg_service: aws_dockercfg
```

And the output I'm seeing on Codeship.

```
# test_bot 
2015-12-29 22:15:07 aws_dockercfg build/pull started
2015-12-29 22:15:58 aws_dockercfg build/pull finished successfully
2015-12-29 22:16:02 aws_dockercfg Logging into AWS ECR
2015-12-29 22:16:03 aws_dockercfg 
2015-12-29 22:16:03 aws_dockercfg Invalid endpoint: https://ecr..amazonaws.com
2015-12-29 22:16:03 aws_dockercfg Writing Docker creds to /tmp/credentials/codeship-dockercfg091915487/codeship-dockercfg062952626
2015-12-29 22:16:03 aws_dockercfg cp: cannot stat '/root/.docker/config.json': No such file or directory
2015-12-29 22:16:06 aws_dockercfg step test_bot running service aws_dockercfg had exit code 1
```

**Comment by bfosberry** [comment]
Hi John, a couple of points

1) You only need to define dockercfg_service in one place that will affect the building of the service. In your case you have declared it in both the service and the step. This won't cause errors but could cause mess and confusion. The service will pull credential delcarations from either the service or the step.

2) `registry` is not a valid command step field, only a push step field. For non-push steps we pull the registry from the image name.

3) In your case it looks like region is not set as part of your encrypted AWS env: `https://ecr..amazonaws.com`. See the repo readme, and add AWS_REGION to your encrypted env, or since its not really a secret, to a non-encrypted env file added to the aws_dockercfg service.

Please feel free to open issues or Codeship support tickets. For urgent issues please open support tickets since it is much easier for us to triage those, and we may miss github issues.

Let me know if this helps

**Comment by johnallen3d** [comment]
Thanks for all of the tips @bfosberry! Clearly I'm still learning my away the platform. I've changed my configuration to just list `dockercfg_service` in the test step and removed the registry entry. I'll get to pushing once I get this part working.

grrrr sometimes `AWS_REGION` sometimes `AWS_DEFAULT_REGION` I've ensured that both are set and get the same results. A couple of things:

1) I notice that the [README.md](https://github.com/codeship-library/aws-ecr-dockercfg-generator/blob/master/README.md) mentions a key of `encrypted_env` and the [documentation](https://codeship.com/documentation/docker/encryption/) mentions `encrypted_env_file`. Originally I had `encrypted_env` so I tried `encrypted_env_file` still no luck.

2) Just to be sure I decrypted my `aws-ecr.env.encrypted` and verified it contained `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

3) I went ahead and added an `env_file` (not encrypted) that included the region and got a bit further, yay!

And the output I'm seeing on Codeship now:

```
2015-12-30 19:01:05 aws_dockercfg build/pull started
2015-12-30 19:01:53 aws_dockercfg build/pull finished successfully
2015-12-30 19:01:56 aws_dockercfg Logging into AWS ECR
2015-12-30 19:01:59 aws_dockercfg Unable to locate credentials. You can configure credentials by running "aws configure".
2015-12-30 19:01:59 aws_dockercfg Writing Docker creds to /tmp/credentials/codeship-dockercfg571231086/codeship-dockercfg195939829
2015-12-30 19:01:59 aws_dockercfg cp: cannot stat '/root/.docker/config.json': No such file or directory
2015-12-30 19:01:59 aws_dockercfg step test_bot running service aws_dockercfg had exit code 1
```

It would seem that no matter how I provide the encrypted credentials they are not being picked up.

I thought it might be helpful to have an open discussion if others ran into similar issues in the future. Say the word and I'll move this discussion over to Codeship support.

**Comment by johnallen3d** [comment]
One more thing, I seem to get a little further when running the steps locally with `jet`

```
> jet steps

{StepStarted=step_name:"test_bot"}
{ContainerRunStdout=step_name:"test_bot" service_name:"aws_dockercfg"}: Logging into AWS ECR
{ContainerRunStdout=step_name:"test_bot" service_name:"aws_dockercfg"}: WARNING: login credentials saved in /root/.docker/config.json
{ContainerRunStdout=step_name:"test_bot" service_name:"aws_dockercfg"}: Login Succeeded
{ContainerRunStdout=step_name:"test_bot" service_name:"aws_dockercfg"}: Writing Docker creds to /tmp/codeship-dockercfg052676433/codeship-dockercfg330696316
{StepFinished=step_name:"test_bot" type:STEP_FINISHED_TYPE_ERROR}
Failed to parse dockercfg: unexpected end of JSON input
```

**Comment by bfosberry** [comment]
Hey John, sorry you are having issues with this.

1) thanks for the PR fixing that in the docs 

2) Are you using the same AES key locally (in ./codeship.aes) as is in your project on codeship.com? You can explicitly specify this with `--key-path`. 

3) if you get an aws configure error that usually means the aws region/access/secret were not visible in the container

It seems odd that it would give a json error. That's usually a volume related error, i.e the file is not where we think it is.

So a good debugging step is to do a `jet load aws_dockercfg` which will build the image for you. Then do a docker run with an unencrypted env attached to the container for AWS creds. You can then try and write a dockercfg from AWS manually. This will verify your creds are correct.

If you're getting a json error it indicates either a local jet issue, or a problem with the dockercfg generated by AWS. Could you bundle up your latest services and steps version for me so I can test it out my end? What version of jet are you using? Make sure you test with the latest version available here: https://codeship.com/documentation/docker/installation/

**Comment by johnallen3d** [comment]
Ok @bfosberry you're response to `#2` pointed me in the right direction. I made the mistake of copying my `.aes` file from another project. :disappointed: Thanks for all your help!

**Comment by bfosberry** [comment]
Awesome! Glad you are sorted, thanks for following up!

**Comment by whyvez** [comment]
It would be great if you merged in the doc changes ASAP where @johnallen3d mentioned that the `encrypted_env_file` field was set wrong. It will frustrate many people as it happened with me. 6 builds later...

<img width="742" alt="screen shot 2016-02-19 at 10 02 10 am" src="https://cloud.githubusercontent.com/assets/1593907/13182645/f4dd5746-d6ef-11e5-8dae-ae4fd7aad227.png">

doc here: https://blog.codeship.com/aws-registry/

**Comment by mlocher** [comment]
@whyvez I just updated the code block on the article, thanks for bringing this up :)
